version: '3.8'

services:
  api:
    build: . # Constroi a imagem a partir do Dockerfile na raiza do projeto
    container_name: geapi # Nome do container
    ports:
      - "8000:8000" # Mapeia a porta 8000 do host para a porta 8000 do container
    volumes:
      - .:/app
    #command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
